// Treść kursu. Każdy tekst to obiekt { pl, ru }.
// summary: lista sekcji { h, pts:{pl:[],ru:[]} }; terms[].def = znaczenie na odwrocie fiszki.
window.COURSE = {
  title: { pl: "Makroekonomia", ru: "Макроэкономика" },
  university: "WSB Gdańsk · dr Elżbieta Kwella",
  examDate: "2027-01-28",

  // Program wykładów z sylabusa — tematy bez materiałów pokazywane jako „wkrótce”.
  program: [
    { n: 1, pl: "Wprowadzenie. Podstawy makro- i mikroekonomii. Rynek, popyt, podaż", ru: "Введение. Основы макро- и микроэкономики. Рынок, спрос, предложение" },
    { n: 2, pl: "Ruch okrężny i rachunek produktu i dochodu narodowego (PKB)", ru: "Кругооборот и счёт национального продукта и дохода (ВВП)" },
    { n: 3, pl: "Trend i cykle koniunkturalne", ru: "Тренд и экономические циклы" },
    { n: 4, pl: "Cykle koniunkturalne w USA i w Polsce", ru: "Экономические циклы в США и Польше" },
    { n: 5, pl: "Model klasyczny i model keynesowski", ru: "Классическая и кейнсианская модели" },
    { n: 6, pl: "Budżet państwa i polityka fiskalna", ru: "Госбюджет и фискальная политика" },
    { n: 7, pl: "Pieniądz i banki", ru: "Деньги и банки" },
    { n: 8, pl: "Bank centralny i polityka pieniężna", ru: "Центральный банк и денежно-кредитная политика" },
    { n: 9, pl: "Model IS-LM", ru: "Модель IS-LM" },
    { n: 10, pl: "Rynek pracy i bezrobocie", ru: "Рынок труда и безработица" },
    { n: 11, pl: "Inflacja", ru: "Инфляция" },
    { n: 12, pl: "Wzrost i rozwój gospodarczy", ru: "Экономический рост и развитие" },
  ],

  topics: [
    {
      id: "w1",
      lecture: 1,
      title: { pl: "Czym jest makroekonomia? Wprowadzenie", ru: "Что такое макроэкономика? Введение" },
      charts: ["adas", "inflation"],
      summary: [
        {
          h: { pl: "Główne problemy makroekonomiczne", ru: "Главные макроэкономические проблемы" },
          pts: {
            pl: [
              "Wszystkie problemy makro sprowadzają się do pytania: jak szybko powinien działać system gospodarczy?",
              "Odpowiedź normatywna: tak szybko, by moce wytwórcze były w pełni wykorzystane (pełne zatrudnienie), a wzrost był bezinflacyjny.",
              "Bezrobocie (cykliczne) = gospodarka działa zbyt wolno: wydatki za małe, nadwyżki towarów, rosną zapasy, faza recesji.",
              "Inflacja = gospodarka działa zbyt szybko: wydatki za duże, niedobory, zasoby w pełni wykorzystane, PKB powyżej potencjalnego, ceny rosną.",
              "Klucz do wysokiej produkcji i zatrudnienia: utrzymanie łącznych wydatków (gospodarstw, firm, państwa, zagranicy) na odpowiednim poziomie.",
            ],
            ru: [
              "Все макропроблемы сводятся к вопросу: насколько быстро должна работать экономическая система?",
              "Нормативный ответ: так, чтобы мощности использовались полностью (полная занятость), а рост был безинфляционным.",
              "Безработица (циклическая) = экономика работает слишком медленно: расходов мало, избыток товаров, растут запасы, фаза рецессии.",
              "Инфляция = экономика работает слишком быстро: расходов слишком много, дефицит, ресурсы задействованы полностью, ВВП выше потенциального, цены растут.",
              "Ключ к высокому выпуску и занятости — поддерживать совокупные расходы (домохозяйств, фирм, государства, заграницы) на нужном уровне.",
            ],
          },
        },
        {
          h: { pl: "Wybory ekonomiczne i systemy", ru: "Экономический выбор и системы" },
          pts: {
            pl: [
              "Trzy problemy społeczeństwa: co produkować? jak produkować? dla kogo (ile kto dostanie)?",
              "Trzy sposoby wyboru: obyczaj i tradycja, proces polityczny (decyduje rząd), proces rynkowy (wybór indywidualny + mechanizm cenowy).",
              "Systemy: kapitalizm amerykański, socjalizm, socjalizm demokratyczny UE (socjokapitalizm), komunizm (tylko proces polityczny).",
            ],
            ru: [
              "Три проблемы общества: что производить? как производить? для кого (кто сколько получит)?",
              "Три способа выбора: обычай и традиция, политический процесс (решает правительство), рыночный процесс (индивидуальный выбор + ценовой механизм).",
              "Системы: американский капитализм, социализм, демократический социализм ЕС (социокапитализм), коммунизм (только политический процесс).",
            ],
          },
        },
        {
          h: { pl: "Rynek, popyt i podaż (mikro)", ru: "Рынок, спрос и предложение (микро)" },
          pts: {
            pl: [
              "Rynek to system współzależnych transakcji kupna/sprzedaży dóbr i usług.",
              "Popyt to „zamiar kupna” — zdolność i chęć kupna przy różnych cenach. Prawo popytu: im niższa cena, tym większa wielkość popytu (efekt substytucji i efekt dochodowy).",
              "Zmiana ceny = ruch po krzywej D. Zmiana gustów, dochodów, cen substytutów i dóbr komplementarnych = przesunięcie całej krzywej D.",
              "Podaż to „skłonność do sprzedaży”. Prawo podaży: po wyższych cenach producenci oferują więcej.",
              "Krzywą S w prawo przesuwają: nowe techniki produkcji, spadek cen czynników produkcji, niższe podatki.",
              "Równowaga (D = S): przy cenie równowagi nie ma ani nadwyżki, ani niedoboru. Przykład komputerów: Q₁ = 10 − P, Q₂ = P → P = 5, Q = 5.",
              "Mechanizm rynkowy: wzrost popytu → wyższa cena → zyski przyciągają producentów → wzrost podaży → spadek ceny i nowa równowaga długookresowa.",
              "A. Smith (1776): „niewidzialna ręka rynku” — niezależni konsumenci sprawiają, że produkuje się to, czego chce społeczeństwo.",
            ],
            ru: [
              "Рынок — система взаимосвязанных сделок купли/продажи товаров и услуг.",
              "Спрос — «намерение купить», способность и желание купить при разных ценах. Закон спроса: чем ниже цена, тем больше величина спроса (эффект замещения и эффект дохода).",
              "Изменение цены = движение по кривой D. Изменение вкусов, доходов, цен заменителей и дополняющих товаров = сдвиг всей кривой D.",
              "Предложение — «склонность продать». Закон предложения: при более высоких ценах производители предлагают больше.",
              "Кривую S вправо сдвигают: новые технологии, удешевление факторов производства, снижение налогов.",
              "Равновесие (D = S): при равновесной цене нет ни избытка, ни дефицита. Пример с компьютерами: Q₁ = 10 − P, Q₂ = P → P = 5, Q = 5.",
              "Рыночный механизм: рост спроса → рост цены → прибыль привлекает производителей → рост предложения → снижение цены и новое долгосрочное равновесие.",
              "А. Смит (1776): «невидимая рука рынка» — независимые потребители добиваются того, что производится нужное обществу.",
            ],
          },
        },
        {
          h: { pl: "Gospodarka w skali makro: AD i AS", ru: "Экономика в макромасштабе: AD и AS" },
          pts: {
            pl: [
              "Makroekonomia dzieli zjawiska na dwie kategorie: wpływające na popyt i wpływające na podaż.",
              "Zagregowany popyt: AD = C + I + G + (X − M). Krzywa AD jest malejąca — spadające ceny zwiększają łączny popyt.",
              "Instrumenty sterowania AD: polityka fiskalna (wydatki rządowe, podatki) i polityka pieniężna (stopy procentowe, kursy walut).",
              "Strona podaży (AS) to możliwości produkcyjne: godziny pracy, produktywność, efektywność zasobów.",
              "SAS (krótki okres) jest rosnąca. LAS (długi okres) jest pionowa na poziomie produkcji potencjalnej Y* (pełne zatrudnienie).",
              "SAS/LAS przesuwają: postęp techniczny, zmiany płac i cen surowców, polityka strukturalna i przemysłowa.",
              "AD = SAS to równowaga krótkookresowa (może być recesja lub przegrzanie). AD = LAS to równowaga długookresowa przy Y* — występuje tylko bezrobocie naturalne.",
            ],
            ru: [
              "Макроэкономика делит явления на две категории: влияющие на спрос и влияющие на предложение.",
              "Совокупный спрос: AD = C + I + G + (X − M). Кривая AD нисходящая — снижение цен увеличивает совокупный спрос.",
              "Инструменты управления AD: фискальная политика (госрасходы, налоги) и денежная политика (процентные ставки, валютные курсы).",
              "Сторона предложения (AS) — производственные возможности: часы труда, производительность, эффективность ресурсов.",
              "SAS (краткосрочная) восходящая. LAS (долгосрочная) вертикальна на уровне потенциального выпуска Y* (полная занятость).",
              "SAS/LAS сдвигают: технический прогресс, изменения зарплат и цен на сырьё, структурная и промышленная политика.",
              "AD = SAS — краткосрочное равновесие (возможна рецессия или перегрев). AD = LAS — долгосрочное равновесие при Y*, есть только естественная безработица.",
            ],
          },
        },
        {
          h: { pl: "Dwusystemowy model: klasycy vs Keynes", ru: "Двухсистемная модель: классики vs Кейнс" },
          pts: {
            pl: [
              "Model klasyczny (A. Smith, 1776): ceny i płace giętkie, analiza długookresowa AD–LAS. Produkcję ogranicza podaż.",
              "U klasyków nierównowaga jest chwilowa: AD < AS → ceny spadają (luka recesyjna), AD > AS → ceny rosną (luka inflacyjna). Rynek sam wraca do Y*.",
              "Wniosek klasyczny: zmiany AD (polityka fiskalna/pieniężna) zmieniają tylko ceny — polityka antycykliczna jest nieskuteczna w długim okresie.",
              "Model keynesowski (J.M. Keynes, 1936): ceny i płace sztywne, analiza krótkookresowa AD–SAS. Produkcję ogranicza popyt.",
              "U Keynesa w recesji (luka recesyjna) wzrost AD zwiększa realny PKB i zatrudnienie, a nie ceny — polityka jest skuteczna w krótkim okresie.",
            ],
            ru: [
              "Классическая модель (А. Смит, 1776): гибкие цены и зарплаты, долгосрочный анализ AD–LAS. Выпуск ограничивает предложение.",
              "У классиков неравновесие временное: AD < AS → цены падают (рецессионный разрыв), AD > AS → цены растут (инфляционный разрыв). Рынок сам возвращается к Y*.",
              "Вывод классиков: изменения AD (фискальная/денежная политика) меняют только цены — антициклическая политика в долгосроке неэффективна.",
              "Кейнсианская модель (Дж. М. Кейнс, 1936): жёсткие цены и зарплаты, краткосрочный анализ AD–SAS. Выпуск ограничивает спрос.",
              "У Кейнса в рецессии рост AD увеличивает реальный ВВП и занятость, а не цены — политика эффективна в краткосроке.",
            ],
          },
        },
        {
          h: { pl: "Jak zamknąć lukę recesyjną i inflacyjną", ru: "Как закрыть рецессионный и инфляционный разрыв" },
          pts: {
            pl: [
              "Luka recesyjna (Y < Y*): 1) spadek płac i cen (SAS w prawo), 2) wzrost wydatków prywatnych, 3) wzrost wydatków rządowych, podaży pieniądza lub cięcie podatków (AD w prawo).",
              "Luka inflacyjna (Y > Y*): 1) wzrost płac i cen (SAS w lewo), 2) spadek wydatków prywatnych, 3) cięcie wydatków rządowych, podaży pieniądza lub podwyżka podatków (AD w lewo).",
              "Metody 1–2 to metody rynkowe (klasycy, liberałowie). Metoda 3 to interwencjonizm państwa (keynesiści; politykę pieniężną popierają też monetaryści).",
              "Samoczynne zamknięcie luki inflacyjnej (SAS w lewo) daje Y* przy wyższych płacach i cenach — gospodarka jest mniej konkurencyjna. Lepiej schłodzić popyt (AD w lewo).",
            ],
            ru: [
              "Рецессионный разрыв (Y < Y*): 1) снижение зарплат и цен (SAS вправо), 2) рост частных расходов, 3) рост госрасходов, денежной массы или снижение налогов (AD вправо).",
              "Инфляционный разрыв (Y > Y*): 1) рост зарплат и цен (SAS влево), 2) снижение частных расходов, 3) сокращение госрасходов, денежной массы или повышение налогов (AD влево).",
              "Методы 1–2 рыночные (классики, либералы). Метод 3 — государственный интервенционизм (кейнсианцы; денежную политику поддерживают и монетаристы).",
              "Если инфляционный разрыв закрывается сам (SAS влево), экономика приходит к Y* при более высоких зарплатах и ценах и теряет конкурентоспособность. Лучше охладить спрос (AD влево).",
            ],
          },
        },
        {
          h: { pl: "Podstawowe prawa ekonomii", ru: "Основные законы экономики" },
          pts: {
            pl: [
              "Paradoks Veblena: popyt na dobra luksusowe rośnie mimo wzrostu ich ceny (efekt prestiżu).",
              "Paradoks Giffena: przy bardzo niskich dochodach popyt na tanie dobro podstawowe (chleb) rośnie mimo wzrostu jego ceny.",
              "Prawo Engla: wraz ze wzrostem dochodów wydatki na żywność rosną wolniej, więc ich udział w wydatkach spada.",
              "Prawo Kopernika-Greshama: „gorszy pieniądz wypiera lepszy” — lepszy jest gromadzony, w obiegu zostaje gorszy.",
              "Prawo malejących przychodów: po pewnym poziomie każda kolejna jednostka czynnika daje coraz mniejszy przyrost produkcji.",
              "Prawo Saya: podaż tworzy własny popyt — ogólna nadprodukcja jest niemożliwa.",
              "Prawo Keynesa: popyt tworzy własną podaż — przyczyną bezrobocia jest za mały popyt globalny, nadprodukcja jest możliwa.",
              "Prawo Okuna: każdy 1 p.p. bezrobocia powyżej stopy naturalnej obniża PNB o ok. 2,5%.",
              "Paradoks oszczędności: gdy wszyscy więcej oszczędzają, spada popyt, produkcja i dochody — ogólny poziom oszczędności może nawet spaść.",
            ],
            ru: [
              "Парадокс Веблена: спрос на предметы роскоши растёт, несмотря на рост их цены (эффект престижа).",
              "Парадокс Гиффена: при очень низких доходах спрос на дешёвый базовый товар (хлеб) растёт, несмотря на рост его цены.",
              "Закон Энгеля: с ростом доходов расходы на еду растут медленнее, поэтому их доля в расходах падает.",
              "Закон Коперника–Грешема: «худшие деньги вытесняют лучшие» — лучшие копят, в обороте остаются худшие.",
              "Закон убывающей отдачи: после определённого уровня каждая следующая единица фактора даёт всё меньший прирост выпуска.",
              "Закон Сэя: предложение создаёт собственный спрос — общее перепроизводство невозможно.",
              "Закон Кейнса: спрос создаёт собственное предложение — безработица вызвана недостатком совокупного спроса, перепроизводство возможно.",
              "Закон Оукена: каждый 1 п.п. безработицы сверх естественного уровня снижает ВНП примерно на 2,5%.",
              "Парадокс бережливости: когда все больше сберегают, падают спрос, выпуск и доходы — общий объём сбережений может даже снизиться.",
            ],
          },
        },
        {
          h: { pl: "Polska w liczbach (RPP i NBP)", ru: "Польша в цифрах (RPP и NBP)" },
          pts: {
            pl: [
              "Rada Polityki Pieniężnej (RPP) ustala stopy procentowe NBP. Cel inflacyjny NBP: 2,5% ± 1 p.p.",
              "Stopy NBP od 09.10.2025: referencyjna 4,50%, lombardowa 5,00%, depozytowa 4,00%.",
              "Szczyt stopy referencyjnej: 6,75% (09.2022), minimum: 0,10% (05.2020).",
              "Inflacja w Polsce: 14,4% (2022), 11,4% (2023), 3,6% (2024); deflacja w latach 2015–2016.",
              "Stopa bezrobocia rejestrowanego: ok. 20% (2002–2004), 5,5% (VIII 2025).",
            ],
            ru: [
              "Совет денежной политики (RPP) устанавливает процентные ставки NBP. Инфляционная цель NBP: 2,5% ± 1 п.п.",
              "Ставки NBP с 09.10.2025: референсная 4,50%, ломбардная 5,00%, депозитная 4,00%.",
              "Пик референсной ставки: 6,75% (09.2022), минимум: 0,10% (05.2020).",
              "Инфляция в Польше: 14,4% (2022), 11,4% (2023), 3,6% (2024); дефляция в 2015–2016 гг.",
              "Уровень зарегистрированной безработицы: около 20% (2002–2004), 5,5% (VIII 2025).",
            ],
          },
        },
      ],
      formulas: [
        { f: "AD = C + I + G + (X − M)", d: { pl: "Zagregowany popyt: konsumpcja + inwestycje + zakupy rządowe + eksport netto", ru: "Совокупный спрос: потребление + инвестиции + госзакупки + чистый экспорт" } },
        { f: "NX = X − M", d: { pl: "Eksport netto", ru: "Чистый экспорт" } },
        { f: "Q₁ = 10 − P,  Q₂ = P  →  P = 5, Q = 5", d: { pl: "Przykład z wykładu: równowaga na rynku komputerów (D = S)", ru: "Пример с лекции: равновесие на рынке компьютеров (D = S)" } },
        { f: "AD < AS → ↓P   |   AD > AS → ↑P", d: { pl: "Niewidzialna ręka rynku: nadwyżka obniża ceny, niedobór je podnosi", ru: "Невидимая рука рынка: избыток снижает цены, дефицит повышает" } },
        { f: "AD = SAS  /  AD = LAS", d: { pl: "Równowaga krótkookresowa / długookresowa (przy Y*)", ru: "Краткосрочное / долгосрочное равновесие (при Y*)" } },
        { f: "Y = m · A", d: { pl: "Keynes: produkcja = mnożnik × wydatki autonomiczne", ru: "Кейнс: выпуск = мультипликатор × автономные расходы" } },
        { f: "1 p.p. (u − u*) → ΔPNB ≈ −2,5%", d: { pl: "Prawo Okuna", ru: "Закон Оукена" } },
        { f: "0 < ΔD/ΔY < 1", d: { pl: "Prawo Engla: dochodowa elastyczność popytu na żywność", ru: "Закон Энгеля: эластичность спроса на еду по доходу" } },
      ],
      terms: [
        { pl: "Makroekonomia", ru: "Макроэкономика", en: "Macroeconomics",
          def: { pl: "Nauka o gospodarce jako całości: produkcji, zatrudnieniu, inflacji i polityce gospodarczej.", ru: "Наука об экономике в целом: выпуск, занятость, инфляция и экономическая политика." } },
        { pl: "Rynek", ru: "Рынок", en: "Market",
          def: { pl: "System współzależnych transakcji kupna/sprzedaży dóbr i usług.", ru: "Система взаимосвязанных сделок купли/продажи товаров и услуг." } },
        { pl: "Popyt", ru: "Спрос", en: "Demand",
          def: { pl: "Zamiar kupna: ilości dobra, które nabywcy chcą i mogą kupić przy różnych cenach w danym czasie.", ru: "Намерение купить: количество товара, которое покупатели хотят и могут купить при разных ценах за период." } },
        { pl: "Podaż", ru: "Предложение", en: "Supply",
          def: { pl: "Skłonność do sprzedaży: ilość dobra oferowana na rynku przy różnych cenach w danym czasie.", ru: "Склонность продать: количество товара, предлагаемое на рынке при разных ценах за период." } },
        { pl: "Cena równowagi", ru: "Равновесная цена", en: "Equilibrium price",
          def: { pl: "Cena, przy której ilość pożądana = ilość oferowana (D = S); nie ma nadwyżki ani niedoboru.", ru: "Цена, при которой величина спроса = величине предложения (D = S); нет ни избытка, ни дефицита." } },
        { pl: "Niewidzialna ręka rynku", ru: "Невидимая рука рынка", en: "Invisible hand",
          def: { pl: "Idea A. Smitha: swobodne ceny i decyzje jednostek same prowadzą gospodarkę do równowagi.", ru: "Идея А. Смита: свободные цены и решения людей сами приводят экономику к равновесию." } },
        { pl: "Zagregowany popyt (AD)", ru: "Совокупный спрос (AD)", en: "Aggregate demand",
          def: { pl: "Łączne ilości dóbr i usług, które wszyscy nabywcy chcą kupić przy danym poziomie cen: C + I + G + NX.", ru: "Общий объём товаров и услуг, который все покупатели хотят купить при данном уровне цен: C + I + G + NX." } },
        { pl: "Krótkookresowa podaż (SAS)", ru: "Краткосрочное предложение (SAS)", en: "Short-run aggregate supply",
          def: { pl: "Łączna produkcja, którą firmy chcą dostarczyć przy różnych poziomach cen; krzywa rosnąca.", ru: "Общий выпуск, который фирмы готовы поставить при разных уровнях цен; восходящая кривая." } },
        { pl: "Długookresowa podaż (LAS)", ru: "Долгосрочное предложение (LAS)", en: "Long-run aggregate supply",
          def: { pl: "Pionowa krzywa na poziomie produkcji potencjalnej, przy pełnym wykorzystaniu mocy wytwórczych.", ru: "Вертикальная кривая на уровне потенциального выпуска при полном использовании мощностей." } },
        { pl: "Produkcja potencjalna (Y*)", ru: "Потенциальный выпуск (Y*)", en: "Potential output",
          def: { pl: "PKB przy pełnym zatrudnieniu — występuje tylko bezrobocie naturalne.", ru: "ВВП при полной занятости — есть только естественная безработица." } },
        { pl: "Luka recesyjna (deflacyjna)", ru: "Рецессионный (дефляционный) разрыв", en: "Recessionary gap",
          def: { pl: "Bieżący PKB poniżej potencjalnego: niewykorzystane moce i bezrobocie przymusowe.", ru: "Текущий ВВП ниже потенциального: простаивающие мощности и вынужденная безработица." } },
        { pl: "Luka inflacyjna", ru: "Инфляционный разрыв", en: "Inflationary gap",
          def: { pl: "Bieżący PKB powyżej potencjalnego: presja płacowa i inflacyjna.", ru: "Текущий ВВП выше потенциального: давление на зарплаты и цены." } },
        { pl: "Polityka fiskalna", ru: "Фискальная политика", en: "Fiscal policy",
          def: { pl: "Wpływanie na AD przez zmiany wydatków rządowych i podatków.", ru: "Влияние на AD через изменение госрасходов и налогов." } },
        { pl: "Polityka pieniężna", ru: "Денежно-кредитная политика", en: "Monetary policy",
          def: { pl: "Wpływanie na AD przez stopy procentowe, kursy walut i podaż pieniądza (bank centralny).", ru: "Влияние на AD через процентные ставки, курсы валют и денежную массу (центробанк)." } },
        { pl: "Polityka dyskrecjonalna", ru: "Дискреционная политика", en: "Discretionary policy",
          def: { pl: "Aktywne kompensowanie przez rząd wahań wydatków prywatnych, by łagodzić recesje i boomy.", ru: "Активная компенсация государством колебаний частных расходов, чтобы смягчать спады и бумы." } },
        { pl: "Prawo Saya", ru: "Закон Сэя", en: "Say's law",
          def: { pl: "Podaż tworzy własny popyt; ogólna nadprodukcja jest niemożliwa.", ru: "Предложение создаёт собственный спрос; общее перепроизводство невозможно." } },
        { pl: "Prawo Okuna", ru: "Закон Оукена", en: "Okun's law",
          def: { pl: "Każdy 1 p.p. bezrobocia ponad stopę naturalną obniża PNB o ok. 2,5%.", ru: "Каждый 1 п.п. безработицы сверх естественного уровня снижает ВНП примерно на 2,5%." } },
        { pl: "Paradoks Giffena", ru: "Парадокс Гиффена", en: "Giffen paradox",
          def: { pl: "Przy bardzo niskich dochodach popyt na tanie dobro podstawowe rośnie mimo wzrostu jego ceny.", ru: "При очень низких доходах спрос на дешёвый базовый товар растёт, несмотря на рост цены." } },
        { pl: "Efekt Veblena", ru: "Эффект Веблена", en: "Veblen effect",
          def: { pl: "Wzrost popytu na dobra luksusowe mimo wzrostu ich ceny (efekt prestiżu).", ru: "Рост спроса на предметы роскоши, несмотря на рост цены (эффект престижа)." } },
        { pl: "Paradoks oszczędności", ru: "Парадокс бережливости", en: "Paradox of thrift",
          def: { pl: "Gdy wszyscy więcej oszczędzają, spada popyt, produkcja i dochody — łączne oszczędności mogą spaść.", ru: "Когда все больше сберегают, падают спрос, выпуск и доходы — суммарные сбережения могут снизиться." } },
        { pl: "RPP", ru: "RPP (Совет денежной политики)", en: "Monetary Policy Council",
          def: { pl: "Rada Polityki Pieniężnej — ustala stopy procentowe NBP; cel inflacyjny 2,5% ± 1 p.p.", ru: "Совет денежной политики — устанавливает ставки NBP; инфляционная цель 2,5% ± 1 п.п." } },
      ],
      quiz: [
        {
          q: { pl: "Problem bezrobocia cyklicznego oznacza, że system gospodarczy działa:", ru: "Проблема циклической безработицы означает, что экономика работает:" },
          a: [{ pl: "zbyt wolno — wydatki są za małe", ru: "слишком медленно — расходов мало" }, { pl: "zbyt szybko — wydatki są za duże", ru: "слишком быстро — расходов слишком много" }, { pl: "z optymalną prędkością", ru: "с оптимальной скоростью" }],
          correct: 0,
          why: { pl: "Przy bezrobociu wydatki są za małe, powstają nadwyżki i rosną zapasy.", ru: "При безработице расходов мало, возникает избыток товаров и растут запасы." },
        },
        {
          q: { pl: "Która cecha opisuje gospodarkę z problemem inflacji?", ru: "Какой признак описывает экономику с проблемой инфляции?" },
          a: [{ pl: "Moce wytwórcze niewykorzystane", ru: "Мощности не используются" }, { pl: "Bieżący PKB powyżej potencjalnego", ru: "Текущий ВВП выше потенциального" }, { pl: "Faza recesji", ru: "Фаза рецессии" }, { pl: "Nadwyżki towarów", ru: "Избыток товаров" }],
          correct: 1,
          why: { pl: "Inflacja: zasoby w pełni wykorzystane, PKB > potencjalny, boom i przegrzanie, ceny rosną.", ru: "Инфляция: ресурсы задействованы полностью, ВВП > потенциального, бум и перегрев, цены растут." },
        },
        {
          q: { pl: "Spadek ceny komputerów powoduje:", ru: "Снижение цены компьютеров вызывает:" },
          a: [{ pl: "przesunięcie krzywej popytu w prawo", ru: "сдвиг кривой спроса вправо" }, { pl: "ruch wzdłuż krzywej popytu (większa wielkość popytu)", ru: "движение вдоль кривой спроса (рост величины спроса)" }, { pl: "przesunięcie krzywej podaży w prawo", ru: "сдвиг кривой предложения вправо" }],
          correct: 1,
          why: { pl: "Zmiana ceny samego dobra to ruch po krzywej. Krzywą przesuwają m.in. dochody, gusty, ceny substytutów.", ru: "Изменение цены самого товара — движение по кривой. Кривую сдвигают доходы, вкусы, цены заменителей и т.д." },
        },
        {
          q: { pl: "Popyt: Q₁ = 10 − P, podaż: Q₂ = P. Cena równowagi wynosi:", ru: "Спрос: Q₁ = 10 − P, предложение: Q₂ = P. Равновесная цена:" },
          a: [{ pl: "3", ru: "3" }, { pl: "5", ru: "5" }, { pl: "7", ru: "7" }, { pl: "10", ru: "10" }],
          correct: 1,
          why: { pl: "10 − P = P → P = 5, Q = 5.", ru: "10 − P = P → P = 5, Q = 5." },
        },
        {
          q: { pl: "Co przesuwa krzywą podaży w prawo?", ru: "Что сдвигает кривую предложения вправо?" },
          a: [{ pl: "Wzrost podatków", ru: "Рост налогов" }, { pl: "Wzrost cen czynników produkcji", ru: "Рост цен факторов производства" }, { pl: "Nowe techniki produkcji", ru: "Новые технологии производства" }],
          correct: 2,
          why: { pl: "Postęp techniczny, tańsze czynniki produkcji i niższe podatki zwiększają podaż.", ru: "Техпрогресс, удешевление факторов и снижение налогов увеличивают предложение." },
        },
        {
          q: { pl: "Który element NIE jest składnikiem AD?", ru: "Что НЕ является компонентом AD?" },
          a: [{ pl: "Wydatki konsumpcyjne (C)", ru: "Потребительские расходы (C)" }, { pl: "Zakupy rządowe (G)", ru: "Госзакупки (G)" }, { pl: "Produkcja potencjalna (Y*)", ru: "Потенциальный выпуск (Y*)" }, { pl: "Eksport netto (X − M)", ru: "Чистый экспорт (X − M)" }],
          correct: 2,
          why: { pl: "AD = C + I + G + (X − M). Y* wyznacza położenie LAS, czyli strona podaży.", ru: "AD = C + I + G + (X − M). Y* задаёт положение LAS, то есть сторону предложения." },
        },
        {
          q: { pl: "Krzywa LAS jest:", ru: "Кривая LAS:" },
          a: [{ pl: "pionowa na poziomie produkcji potencjalnej", ru: "вертикальна на уровне потенциального выпуска" }, { pl: "pozioma przy stałych cenach", ru: "горизонтальна при постоянных ценах" }, { pl: "malejąca", ru: "нисходящая" }],
          correct: 0,
          why: { pl: "W długim okresie produkcję wyznaczają zasoby i technologia, a nie poziom cen.", ru: "В долгосрочном периоде выпуск определяют ресурсы и технологии, а не уровень цен." },
        },
        {
          q: { pl: "W modelu klasycznym (AD–LAS) wzrost AD powoduje:", ru: "В классической модели (AD–LAS) рост AD вызывает:" },
          a: [{ pl: "wzrost realnego PKB", ru: "рост реального ВВП" }, { pl: "tylko wzrost cen", ru: "только рост цен" }, { pl: "spadek bezrobocia", ru: "снижение безработицы" }],
          correct: 1,
          why: { pl: "Ceny są giętkie, gospodarka jest zawsze przy Y* — zmiany AD dają tylko zmiany nominalne.", ru: "Цены гибкие, экономика всегда на Y* — изменения AD дают только номинальные изменения." },
        },
        {
          q: { pl: "Keynesowski model krótkookresowy zakłada:", ru: "Кейнсианская краткосрочная модель предполагает:" },
          a: [{ pl: "giętkie ceny i płace", ru: "гибкие цены и зарплаты" }, { pl: "sztywne ceny i płace", ru: "жёсткие цены и зарплаты" }, { pl: "brak wpływu popytu na produkcję", ru: "отсутствие влияния спроса на выпуск" }],
          correct: 1,
          why: { pl: "Przy sztywnych cenach wzrost AD w recesji zwiększa realną produkcję i zatrudnienie.", ru: "При жёстких ценах рост AD в рецессии увеличивает реальный выпуск и занятость." },
        },
        {
          q: { pl: "Kto opisał „niewidzialną rękę rynku”?", ru: "Кто описал «невидимую руку рынка»?" },
          a: [{ pl: "J.M. Keynes", ru: "Дж. М. Кейнс" }, { pl: "A. Smith", ru: "А. Смит" }, { pl: "A. Okun", ru: "А. Оукен" }, { pl: "J.B. Say", ru: "Ж.-Б. Сэй" }],
          correct: 1,
          why: { pl: "Adam Smith, „Bogactwo narodów”, 1776.", ru: "Адам Смит, «Богатство народов», 1776." },
        },
        {
          q: { pl: "Jak polityką zamknąć lukę recesyjną (metoda keynesowska)?", ru: "Как политикой закрыть рецессионный разрыв (по Кейнсу)?" },
          a: [{ pl: "Podnieść podatki", ru: "Повысить налоги" }, { pl: "Zmniejszyć podaż pieniądza", ru: "Сократить денежную массу" }, { pl: "Zwiększyć wydatki rządowe lub obniżyć podatki", ru: "Увеличить госрасходы или снизить налоги" }],
          correct: 2,
          why: { pl: "To przesuwa AD w prawo, w stronę Y*.", ru: "Это сдвигает AD вправо, к Y*." },
        },
        {
          q: { pl: "Dlaczego politycy wolą nie czekać, aż luka inflacyjna zamknie się sama?", ru: "Почему политики не ждут, пока инфляционный разрыв закроется сам?" },
          a: [{ pl: "Bo gospodarka wraca do Y* przy wyższych płacach i cenach i traci konkurencyjność", ru: "Потому что экономика вернётся к Y* при более высоких зарплатах и ценах и потеряет конкурентоспособность" }, { pl: "Bo bezrobocie spadnie do zera", ru: "Потому что безработица упадёт до нуля" }, { pl: "Bo realny PKB wzrośnie", ru: "Потому что реальный ВВП вырастет" }],
          correct: 0,
          why: { pl: "Lepiej schłodzić popyt (AD w lewo) i zdławić presję inflacyjno-płacową w zarodku.", ru: "Лучше охладить спрос (AD влево) и подавить инфляционное давление в зародыше." },
        },
        {
          q: { pl: "„Podaż tworzy swój własny popyt” — to prawo:", ru: "«Предложение создаёт собственный спрос» — это закон:" },
          a: [{ pl: "Keynesa", ru: "Кейнса" }, { pl: "Saya", ru: "Сэя" }, { pl: "Engla", ru: "Энгеля" }],
          correct: 1,
          why: { pl: "Keynes twierdził odwrotnie: popyt tworzy podaż.", ru: "Кейнс утверждал обратное: спрос создаёт предложение." },
        },
        {
          q: { pl: "Popyt na dobro luksusowe rośnie, bo jego cena wzrosła. To:", ru: "Спрос на предмет роскоши растёт, потому что его цена выросла. Это:" },
          a: [{ pl: "paradoks Giffena", ru: "парадокс Гиффена" }, { pl: "efekt Veblena", ru: "эффект Веблена" }, { pl: "prawo Engla", ru: "закон Энгеля" }],
          correct: 1,
          why: { pl: "Giffen dotyczy tanich dóbr podstawowych przy niskich dochodach, Veblen — dóbr luksusowych.", ru: "Гиффен — дешёвые базовые товары при низких доходах, Веблен — предметы роскоши." },
        },
        {
          q: { pl: "Według prawa Okuna 1 p.p. bezrobocia ponad stopę naturalną obniża PNB o ok.:", ru: "По закону Оукена 1 п.п. безработицы сверх естественного уровня снижает ВНП примерно на:" },
          a: [{ pl: "0,5%", ru: "0,5%" }, { pl: "1%", ru: "1%" }, { pl: "2,5%", ru: "2,5%" }, { pl: "10%", ru: "10%" }],
          correct: 2,
          why: { pl: "Tak podaje wykład (dane dla USA).", ru: "Так сказано в лекции (данные по США)." },
        },
        {
          q: { pl: "Cel inflacyjny NBP wynosi:", ru: "Инфляционная цель NBP:" },
          a: [{ pl: "2% ± 0,5 p.p.", ru: "2% ± 0,5 п.п." }, { pl: "2,5% ± 1 p.p.", ru: "2,5% ± 1 п.п." }, { pl: "3,5% ± 1 p.p.", ru: "3,5% ± 1 п.п." }],
          correct: 1,
          why: { pl: "Cel ciągły NBP: 2,5% z pasmem odchyleń ± 1 p.p.", ru: "Постоянная цель NBP: 2,5% с допустимым отклонением ± 1 п.п." },
        },
      ],
    },
  ],

  // Dane do wykresów (źródło: materiały wykładowe, GUS, NBP)
  data: {
    inflation: [[2003,0.8],[2004,3.5],[2005,2.1],[2006,1.0],[2007,2.5],[2008,4.2],[2009,3.5],[2010,2.6],[2011,4.3],[2012,3.7],[2013,0.9],[2014,0.0],[2015,-0.9],[2016,-0.6],[2017,2.0],[2018,1.6],[2019,2.3],[2020,3.4],[2021,5.1],[2022,14.4],[2023,11.4],[2024,3.6]],
  },
};
